### ISSUE TITLE
Media Player failed to load YouTube videos

### ISSUE THREAD

**Issue by CerealYe** [samuelmaddock/gm-mediaplayer#52]
So here's the bug I just reported, I tried to request some YouTube videos I want and it doesn't work, I get a error message in the chat that says "[Request Error] Failed to load YouTube [unsuccessful]".
[
![image](https://user-images.githubusercontent.com/59343254/221436663-f73a1de0-722a-4400-b38c-ad603e4b9cb3.png)
](url)
I'm actually on chromium beta and it still doesn't work.
Not only that, but even Twitch live streams or clips doesn't work either. It only works with supported file urls like mp3, wav, ogg, jpg, png, and webm.

Sam, or who ever contributes this mod, please fix

**Comment by samuelmaddock** [comment]
Oddly I was only able to reproduce the issue once, even with the metadata cache disabled. I might have fixed this in 9cf510f9392739388b178c4fce91e90f633c66db

I've published an update on workshop. Let me know if it's fixed.

**Comment by CerealYe** [comment]
I tried to request YouTube video after this update, and it doesn't look like it's fixed.
![image](https://user-images.githubusercontent.com/59343254/222237567-245f94cb-c2e9-40c1-bad8-bd51dfbc103f.png)

**Comment by CerealYe** [comment]
Finally, it actually works! It's been 3 weeks, now I can watch any videos on gmod!
![20230322130120_1](https://user-images.githubusercontent.com/59343254/226899380-1d51ffee-397a-4271-8dcd-362b75b2d39e.jpg)
Thank you, Sam! You're the best!

**Comment by Zvbhrf** [comment]
The problem still exists.
I have my own server, which I haven't updated for a while (about 1-3+ gmod updates, I don't know 😄)
I have a friend, who also has his own server too, which was running on the latest version.

He said that on his server mediaplayer gives this error and it's because of gmod updates. He tried to fix it but without any success.
I didn't notice this error on my own server until the June update (Wed, June 28), in which I had to update the server because players couldn't join.
After an update, mediaplayer on my server got broken with the same error: "unsuccessfull" on requests.
![image](https://github.com/samuelmaddock/gm-mediaplayer/assets/79792873/cca7d4d0-e60a-4e03-af01-b0b4ef273aed)


I heard that mediaplayer on singleplayer still works, so I decided to check it:
I installed mediaplayer on my local server, updated the server to the latest update, ran it, and.. the mediaplayer wasn't working. Got "unsuccessfull" on requests.
I went to singleplayer and got this error (which was already reported: #56):
![image](https://github.com/samuelmaddock/gm-mediaplayer/assets/79792873/b2e3e629-6f52-41e3-8c4d-79ea2f027220)

I tried to debug mediaplayer and I think the problem is in the YouTube's service Fetch function, maybe HTTP was updated in one of the gmod updates. I don't know in which one, because I don't follow updates.

(Local server version, if necessary)
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 21:14:04 Jun 27 2023 (8998) (4000)
GMod version 2023.06.28, branch: unknown
Windows 32bit Dedicated Server

(Linux server version, the running server)
![image](https://github.com/samuelmaddock/gm-mediaplayer/assets/79792873/8ec43e61-0feb-4aa6-a85e-44f75303ed34)

(I apologize for any errors that may be in the issue, because I am not a native English speaker. I hope everything is clear)
